// GENERATED FILE — do not edit by hand.
// Source: docs/client-fields.md · Regenerate: node scripts/gen-field-catalog.mjs
//
// Hand-transcribing 100 fields x 7 roles is precisely where one
// mistyped dash puts TAG's management fee on a client's screen, so the visibility
// table is parsed from the doc rather than retyped. test/field-catalog-drift.test.ts
// re-parses the doc and fails if this file and the doc disagree.

import type { Role } from "@/lib/auth/roles";

/** `on` shows by default · `available` is opt-in · `never` is not selectable at any price. */
export type FieldVisibility = "on" | "available" | "never";

export type FieldDefinition = {
  id: string;
  label: string;
  section: string;
  /** Roles absent from this map are `never` — see visibilityOf(). */
  visibility: Partial<Record<Role, FieldVisibility>>;
};

export const FIELD_CATALOG: Record<string, FieldDefinition> = {
  "client.name": {
    id: "client.name",
    label: "Client name",
    section: "Identity & commercial",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "on",
      client_owner: "on",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "client.company": {
    id: "client.company",
    label: "Firm name",
    section: "Identity & commercial",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "on",
      client_owner: "on",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "client.locationId": {
    id: "client.locationId",
    label: "GHL location — the tenant key",
    section: "Identity & commercial",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "never",
      client_manager: "available",
      client_closer: "never",
    },
  },
  "client.industry": {
    id: "client.industry",
    label: "Tax prep · CPA · EA · bookkeeping",
    section: "Identity & commercial",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "never",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "client.region": {
    id: "client.region",
    label: "Territory",
    section: "Identity & commercial",
    visibility: {
      tag_exec: "available",
      tag_csm: "available",
      tag_sales_manager: "on",
      tag_sales: "on",
      client_owner: "never",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "client.size": {
    id: "client.size",
    label: "Solo · 2–10 · 11–50 · 50+",
    section: "Identity & commercial",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "never",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "client.tier": {
    id: "client.tier",
    label: "Service package",
    section: "Identity & commercial",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "on",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "contract.startDate": {
    id: "contract.startDate",
    label: "Engagement start",
    section: "Identity & commercial",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "on",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "contract.renewalDate": {
    id: "contract.renewalDate",
    label: "Next renewal",
    section: "Identity & commercial",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "on",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "contract.monthsActive": {
    id: "contract.monthsActive",
    label: "Tenure",
    section: "Identity & commercial",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "available",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "contract.paymentStatus": {
    id: "contract.paymentStatus",
    label: "current · late · failed",
    section: "Identity & commercial",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "never",
      client_owner: "never",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "contract.mrr": {
    id: "contract.mrr",
    label: "Management fee / retainer",
    section: "Margin — TAG-internal only",
    visibility: {
      tag_exec: "on",
      tag_csm: "available",
      tag_sales_manager: "on",
      tag_sales: "available",
      client_owner: "never",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "econ.feeToSpendRatio": {
    id: "econ.feeToSpendRatio",
    label: "Fee ÷ ad spend",
    section: "Margin — TAG-internal only",
    visibility: {
      tag_exec: "on",
      tag_csm: "never",
      tag_sales_manager: "on",
      tag_sales: "never",
      client_owner: "never",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "contact.name": {
    id: "contact.name",
    label: "Primary contact",
    section: "People & assignment",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "on",
      client_owner: "never",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "contact.email": {
    id: "contact.email",
    label: "Email",
    section: "People & assignment",
    visibility: {
      tag_exec: "available",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "on",
      client_owner: "never",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "contact.phone": {
    id: "contact.phone",
    label: "Direct line",
    section: "People & assignment",
    visibility: {
      tag_exec: "available",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "on",
      client_owner: "never",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "assign.csm": {
    id: "assign.csm",
    label: "Assigned CSM",
    section: "People & assignment",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "available",
      client_closer: "never",
    },
  },
  "assign.salesRep": {
    id: "assign.salesRep",
    label: "Who sold TAG",
    section: "People & assignment",
    visibility: {
      tag_exec: "on",
      tag_csm: "available",
      tag_sales_manager: "on",
      tag_sales: "on",
      client_owner: "never",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "assign.closers": {
    id: "assign.closers",
    label: "Fractional closers on account",
    section: "People & assignment",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "assign.execSponsor": {
    id: "assign.execSponsor",
    label: "Founder sponsor",
    section: "People & assignment",
    visibility: {
      tag_exec: "on",
      tag_csm: "available",
      tag_sales_manager: "available",
      tag_sales: "never",
      client_owner: "never",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "link.ghlLocation": {
    id: "link.ghlLocation",
    label: "GHL sub-account",
    section: "System deep links",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "never",
      client_manager: "on",
      client_closer: "available",
    },
  },
  "link.metaAdAccount": {
    id: "link.metaAdAccount",
    label: "Meta ad account",
    section: "System deep links",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "never",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "link.googleAdsCustomer": {
    id: "link.googleAdsCustomer",
    label: "Google Ads customer",
    section: "System deep links",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "never",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "link.slackChannel": {
    id: "link.slackChannel",
    label: "Shared Slack channel",
    section: "System deep links",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "available",
      client_closer: "never",
    },
  },
  "link.vsl": {
    id: "link.vsl",
    label: "Live VSL URL",
    section: "System deep links",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "on",
      client_owner: "on",
      client_manager: "available",
      client_closer: "available",
    },
  },
  "link.calendar": {
    id: "link.calendar",
    label: "Booking calendar",
    section: "System deep links",
    visibility: {
      tag_exec: "available",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "on",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "spend.actual": {
    id: "spend.actual",
    label: "Ad spend · *channel split*",
    section: "Spend & pacing",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "on",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "spend.budget": {
    id: "spend.budget",
    label: "Approved budget",
    section: "Spend & pacing",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "spend.remaining": {
    id: "spend.remaining",
    label: "Budget − actual",
    section: "Spend & pacing",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "spend.pacePct": {
    id: "spend.pacePct",
    label: "Actual ÷ expected-to-date",
    section: "Spend & pacing",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "never",
      client_owner: "available",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "spend.projectedEom": {
    id: "spend.projectedEom",
    label: "Run-rate projection",
    section: "Spend & pacing",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "never",
      client_owner: "available",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "spend.dailyAvg": {
    id: "spend.dailyAvg",
    label: "Avg daily spend",
    section: "Spend & pacing",
    visibility: {
      tag_exec: "available",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "available",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "spend.capStatus": {
    id: "spend.capStatus",
    label: "under · on_pace · over · capped_out",
    section: "Spend & pacing",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "spend.channelMix": {
    id: "spend.channelMix",
    label: "Meta ÷ Google share",
    section: "Spend & pacing",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "never",
      client_owner: "available",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "traffic.impressions": {
    id: "traffic.impressions",
    label: "Impressions · *split*",
    section: "Traffic & creative",
    visibility: {
      tag_exec: "available",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "traffic.clicks": {
    id: "traffic.clicks",
    label: "Clicks · *split*",
    section: "Traffic & creative",
    visibility: {
      tag_exec: "available",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "traffic.ctr": {
    id: "traffic.ctr",
    label: "Click-through rate",
    section: "Traffic & creative",
    visibility: {
      tag_exec: "available",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "traffic.cpm": {
    id: "traffic.cpm",
    label: "Cost per 1k impressions",
    section: "Traffic & creative",
    visibility: {
      tag_exec: "available",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "available",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "traffic.cpc": {
    id: "traffic.cpc",
    label: "Cost per click",
    section: "Traffic & creative",
    visibility: {
      tag_exec: "available",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "available",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "creative.activeCount": {
    id: "creative.activeCount",
    label: "Live ads",
    section: "Traffic & creative",
    visibility: {
      tag_exec: "available",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "available",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "creative.frequency": {
    id: "creative.frequency",
    label: "Avg frequency — fatigue signal",
    section: "Traffic & creative",
    visibility: {
      tag_exec: "available",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "never",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "creative.daysSinceRefresh": {
    id: "creative.daysSinceRefresh",
    label: "Days since new creative",
    section: "Traffic & creative",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "never",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "funnel.vslViews": {
    id: "funnel.vslViews",
    label: "VSL views",
    section: "Funnel",
    visibility: {
      tag_exec: "available",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "funnel.vslCompletion": {
    id: "funnel.vslCompletion",
    label: "Watched to end %",
    section: "Funnel",
    visibility: {
      tag_exec: "available",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "funnel.lpVisits": {
    id: "funnel.lpVisits",
    label: "Landing page visits",
    section: "Funnel",
    visibility: {
      tag_exec: "never",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "funnel.lpConversion": {
    id: "funnel.lpConversion",
    label: "Visit → form %",
    section: "Funnel",
    visibility: {
      tag_exec: "available",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "funnel.formSubmissions": {
    id: "funnel.formSubmissions",
    label: "Raw form fills",
    section: "Funnel",
    visibility: {
      tag_exec: "available",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "funnel.leads": {
    id: "funnel.leads",
    label: "Qualified leads · *split*",
    section: "Funnel",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "on",
      client_owner: "on",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "funnel.leadQuality": {
    id: "funnel.leadQuality",
    label: "Quality score 1–10",
    section: "Funnel",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "available",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "funnel.cpl": {
    id: "funnel.cpl",
    label: "Cost per lead · *split*",
    section: "Funnel",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "on",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "funnel.bookedCalls": {
    id: "funnel.bookedCalls",
    label: "Consults booked",
    section: "Funnel",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "on",
      client_owner: "on",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "funnel.bookingRate": {
    id: "funnel.bookingRate",
    label: "Lead → booked %",
    section: "Funnel",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "funnel.dqPreCall": {
    id: "funnel.dqPreCall",
    label: "DQ'd before the call — *targeting*",
    section: "Funnel",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "available",
      client_owner: "available",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "funnel.dqOnCall": {
    id: "funnel.dqOnCall",
    label: "DQ'd on the call — *qualification*",
    section: "Funnel",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "available",
      client_owner: "available",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "funnel.costPerBooked": {
    id: "funnel.costPerBooked",
    label: "Cost per booked call",
    section: "Funnel",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "slack.awaitingReply": {
    id: "slack.awaitingReply",
    label: "Newest message is the client's, unanswered",
    section: "Client channel — Slack",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "never",
      client_owner: "never",
      client_manager: "available",
      client_closer: "never",
    },
  },
  "slack.awaitingHours": {
    id: "slack.awaitingHours",
    label: "How long they have waited",
    section: "Client channel — Slack",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "never",
      client_owner: "never",
      client_manager: "available",
      client_closer: "never",
    },
  },
  "slack.medianResponseHours": {
    id: "slack.medianResponseHours",
    label: "Median TAG reply time",
    section: "Client channel — Slack",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "never",
      client_owner: "available",
      client_manager: "available",
      client_closer: "never",
    },
  },
  "slack.lastActivityAt": {
    id: "slack.lastActivityAt",
    label: "Last message either way",
    section: "Client channel — Slack",
    visibility: {
      tag_exec: "available",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "never",
      client_owner: "available",
      client_manager: "available",
      client_closer: "never",
    },
  },
  "slack.botPresent": {
    id: "slack.botPresent",
    label: "Bot is a member of the channel",
    section: "Client channel — Slack",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "never",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "sales.speedToLead": {
    id: "sales.speedToLead",
    label: "Median lead → first contact",
    section: "Sales execution — the fractional team",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "sales.callsTaken": {
    id: "sales.callsTaken",
    label: "Calls held",
    section: "Sales execution — the fractional team",
    visibility: {
      tag_exec: "available",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "sales.showRate": {
    id: "sales.showRate",
    label: "Show rate",
    section: "Sales execution — the fractional team",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "sales.noShowRate": {
    id: "sales.noShowRate",
    label: "No-show rate",
    section: "Sales execution — the fractional team",
    visibility: {
      tag_exec: "available",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "never",
      client_owner: "available",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "sales.closeRate": {
    id: "sales.closeRate",
    label: "Close rate",
    section: "Sales execution — the fractional team",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "sales.closes": {
    id: "sales.closes",
    label: "Deals closed",
    section: "Sales execution — the fractional team",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "on",
      client_owner: "on",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "sales.avgDealSize": {
    id: "sales.avgDealSize",
    label: "Avg advisory package",
    section: "Sales execution — the fractional team",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "on",
      client_owner: "on",
      client_manager: "on",
      client_closer: "available",
    },
  },
  "sales.revenueClosed": {
    id: "sales.revenueClosed",
    label: "Client revenue closed",
    section: "Sales execution — the fractional team",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "on",
      client_owner: "on",
      client_manager: "on",
      client_closer: "available",
    },
  },
  "sales.pipelineOpen": {
    id: "sales.pipelineOpen",
    label: "Open opportunity value",
    section: "Sales execution — the fractional team",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "on",
      client_closer: "on",
    },
  },
  "econ.roas": {
    id: "econ.roas",
    label: "Revenue ÷ ad spend — joined on `utmAdId`",
    section: "Unit economics",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "on",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "econ.cac": {
    id: "econ.cac",
    label: "Ad spend ÷ closes",
    section: "Unit economics",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "econ.ltvCac": {
    id: "econ.ltvCac",
    label: "LTV : CAC ratio",
    section: "Unit economics",
    visibility: {
      tag_exec: "on",
      tag_csm: "available",
      tag_sales_manager: "on",
      tag_sales: "available",
      client_owner: "available",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "econ.paybackMonths": {
    id: "econ.paybackMonths",
    label: "Months to recover CAC",
    section: "Unit economics",
    visibility: {
      tag_exec: "on",
      tag_csm: "available",
      tag_sales_manager: "on",
      tag_sales: "never",
      client_owner: "available",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "econ.revenueLifetime": {
    id: "econ.revenueLifetime",
    label: "Lifetime attributed revenue",
    section: "Unit economics",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "on",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "econ.spendLifetime": {
    id: "econ.spendLifetime",
    label: "Lifetime ad spend",
    section: "Unit economics",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "health.status": {
    id: "health.status",
    label: "healthy · at-risk · critical",
    section: "Health, risk & benchmark",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "on",
      client_owner: "available",
      client_manager: "available",
      client_closer: "never",
    },
  },
  "health.reason": {
    id: "health.reason",
    label: "Which rule fired",
    section: "Health, risk & benchmark",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "available",
      client_manager: "available",
      client_closer: "never",
    },
  },
  "health.trend": {
    id: "health.trend",
    label: "Direction vs. prior period",
    section: "Health, risk & benchmark",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "available",
      client_closer: "never",
    },
  },
  "health.benchmark": {
    id: "health.benchmark",
    label: "Cohort percentile",
    section: "Health, risk & benchmark",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "risk.deliveryStalls": {
    id: "risk.deliveryStalls",
    label: "Won but delivery not marked",
    section: "Health, risk & benchmark",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "available",
      client_owner: "never",
      client_manager: "available",
      client_closer: "never",
    },
  },
  "risk.escalation": {
    id: "risk.escalation",
    label: "Escalation flag — Story 3.6",
    section: "Health, risk & benchmark",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "available",
      client_owner: "never",
      client_manager: "available",
      client_closer: "never",
    },
  },
  "risk.escalationReason": {
    id: "risk.escalationReason",
    label: "What triggered it",
    section: "Health, risk & benchmark",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "available",
      client_owner: "never",
      client_manager: "available",
      client_closer: "never",
    },
  },
  "risk.slaBreaches": {
    id: "risk.slaBreaches",
    label: "Missed SLAs, period",
    section: "Health, risk & benchmark",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "never",
      client_owner: "never",
      client_manager: "available",
      client_closer: "never",
    },
  },
  "data.freshness": {
    id: "data.freshness",
    label: "Last successful sync — Story 4.5",
    section: "Data integrity — per client",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "available",
      client_closer: "available",
    },
  },
  "data.metaSync": {
    id: "data.metaSync",
    label: "ok · stale · failed · not_connected",
    section: "Data integrity — per client",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "available",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "data.googleSync": {
    id: "data.googleSync",
    label: "ok · stale · failed · not_connected",
    section: "Data integrity — per client",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "available",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "data.ghlSync": {
    id: "data.ghlSync",
    label: "ok · stale · failed · not_connected",
    section: "Data integrity — per client",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "available",
      client_manager: "available",
      client_closer: "never",
    },
  },
  "data.pixelStatus": {
    id: "data.pixelStatus",
    label: "Conversion tracking firing",
    section: "Data integrity — per client",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "never",
      tag_sales: "never",
      client_owner: "never",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "quality.attributionGap": {
    id: "quality.attributionGap",
    label: "Platform-reported vs. GHL actual",
    section: "Data integrity — per client",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "never",
      client_owner: "never",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "onboard.stage": {
    id: "onboard.stage",
    label: "Fulfillment stage PR1–AP5",
    section: "Onboarding & launch",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "onboard.daysInStage": {
    id: "onboard.daysInStage",
    label: "Time in current stage",
    section: "Onboarding & launch",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "never",
      client_owner: "available",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "onboard.readinessPct": {
    id: "onboard.readinessPct",
    label: "Checklist completion",
    section: "Onboarding & launch",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "onboard.blockers": {
    id: "onboard.blockers",
    label: "Open blockers",
    section: "Onboarding & launch",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "onboard.targetLaunch": {
    id: "onboard.targetLaunch",
    label: "Scheduled launch date",
    section: "Onboarding & launch",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "on",
      tag_sales: "on",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "onboard.daysSinceLaunch": {
    id: "onboard.daysSinceLaunch",
    label: "Days live",
    section: "Onboarding & launch",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "on",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "ops.lastContact": {
    id: "ops.lastContact",
    label: "Last CSM touch",
    section: "Operational",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "on",
      client_owner: "never",
      client_manager: "available",
      client_closer: "never",
    },
  },
  "ops.nextReview": {
    id: "ops.nextReview",
    label: "Scheduled check-in",
    section: "Operational",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "on",
      client_owner: "on",
      client_manager: "available",
      client_closer: "never",
    },
  },
  "ops.priority": {
    id: "ops.priority",
    label: "high · normal · low",
    section: "Operational",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "never",
      client_manager: "never",
      client_closer: "never",
    },
  },
  "ops.notes": {
    id: "ops.notes",
    label: "Internal notes",
    section: "Operational",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "available",
      client_owner: "never",
      client_manager: "available",
      client_closer: "never",
    },
  },
  "ops.openIssues": {
    id: "ops.openIssues",
    label: "Open bug/issue count",
    section: "Operational",
    visibility: {
      tag_exec: "on",
      tag_csm: "on",
      tag_sales_manager: "available",
      tag_sales: "never",
      client_owner: "available",
      client_manager: "never",
      client_closer: "never",
    },
  },
};

export const FIELD_IDS = Object.keys(FIELD_CATALOG);
